"""Add timestamp to Vote model

Revision ID: 24450dd8fd94
Revises: ccb05c290401
Create Date: 2024-08-01 15:58:58.656343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24450dd8fd94'
down_revision = 'ccb05c290401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
